[package]
name = "trie"
version.workspace = true
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
parking_lot = "0.12"

[features]
serde = ["dep:serde"]

[dev-dependencies]
serde_json = "1.0"
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "trie_bench"
harness = false
