#![allow(unused)] //TODO_JDB REMOVE THIS
use crate::error::Error;
use crate::facts as fx;

use crate::index_engine::source_info::IndexSourceInfo;
use crate::index_engine::{FunctionSummary, IndexFacts, taint_index};
use crate::{
    codegen::{CallResolutionStrategy, RETURN_INDEX, codegen_program},
    languages::tree_sitter,
};
use anyhow::{Context, Result};
use ctadl_ir::graph::DirectedGraph;
use ctadl_ir::{Exp, StatementKind, VariableRef, ssa};
use ctadl_ir::{Program, ProgramInfo};
use std::path::{Path, PathBuf};

pub(crate) fn init_test_logging() {
    let _ = env_logger::builder()
        .filter_level(log::LevelFilter::Debug) // This forces it to Debug
        .is_test(true)
        .try_init();
}

pub(crate) fn get_full_path(filename: &str) -> Result<PathBuf> {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));

    // Now just append the folders from the crate root
    path.push("tests");
    path.push("c");
    path.push(filename);
    Ok(path)
}

/* Compile a program from a string. */
pub(crate) fn program_from_string(src: &str) -> (Program, String) {
    let result = tree_sitter::parse_c_program(src).expect("Failed to parse C program.");
    assert!(
        !result.1,
        "Input Program failed to parse without error from Tree-sitter"
    );
    (result.0, result.2)
}

/* Compile a program from a string. */
pub(crate) fn program_from_string_no_check(src: &str) -> Program {
    program_from_string(src).0
}

/* Compile a program from a file. */
pub(crate) fn program_from_file<P: AsRef<Path>>(filename: P) -> Result<Program> {
    let path = filename.as_ref();

    // Read the file, and if it fails, attach a helpful message before returning
    let contents = std::fs::read_to_string(path)
        .with_context(|| format!("Failed to load source file: {}", path.display()))?;
    let program = tree_sitter::parse_c_program(&contents)?;
    Ok(program.0)
}

/* Common output for when tests fail. */
pub(crate) fn check_fail_str(prog_str: &str, msg: &str) {
    log::error!("TEST FAIL: {msg}");
    log::error!("\t{prog_str}");
}

pub(crate) fn check_fail(prog: &Program, msg: &str) {
    let prog_str = prog.to_string();
    check_fail_str(&prog_str, msg);
}

/* A test to check a particular program parsed N functions. */
pub(crate) fn check_function_count(prog: &Program, count: usize) -> bool {
    let len = prog.functions.len();
    if len != count {
        let err = format!("{} functions in parsed program, expected {}.", len, count);
        check_fail(prog, &err);
        return false;
    }
    true
}

/* Checks that count number of blocks exist in the program.
  Implicitly checks for the existance of only 1 functions.
*/
pub(crate) fn check_block_count(prog: &Program, count: usize) -> bool {
    if !check_function_count(prog, 1) {
        return false;
    }
    let Some(fun) = prog.functions.functions.raw.first() else {
        return false;
    };
    let len = fun.blocks.num_nodes();

    if len != count {
        let err = format!("{} blocks in parsed function, expected {}.", len, count);
        check_fail(prog, &err);
        return false;
    }
    true
}

pub(crate) fn debug_output_blocks(prog: &Program) {
    let Some(fun) = prog.functions.functions.raw.first() else {
        log::warn!("No functions in program");
        return;
    };
    //let mut idx = 0;
    for (idx, block) in fun.blocks.as_slice().into_iter().enumerate() {
        log::info!("BLOCK {}: {}", idx, block);
        //  idx += 1;
    }
}
/* This function is intended to run on Program objects generated by
parsing a single function and will search all blocks for a
particular assignment. */
pub(crate) fn check_assign<I>(
    prog: &Program,
    dst: &str,
    src_strs: I,
    block_id: Option<usize>,
) -> bool
where
    I: IntoIterator<Item = &'static str>,
{
    let srcs: Vec<Exp> = src_strs
        .into_iter()
        .map(|s| Exp::from(VariableRef::new_local(String::from(s))))
        .collect();
    let var = VariableRef::new_local(String::from(dst));
    let assign = StatementKind::assign(var, srcs);

    if !check_function_count(prog, 1) {
        return false;
    }
    let Some(fun) = prog.functions.functions.raw.first() else {
        return false;
    };
    //for block in fun.blocks.iter() {
    for (i, block) in fun.blocks.iter().enumerate() {
        // You can now check 'i' before proceeding
        if let Some(req_block) = block_id
            && i != req_block
        {
            continue;
        }
        for stmt in block.statements.iter() {
            if let StatementKind::Assign { .. } = &stmt.kind
                && stmt.kind == assign
            {
                return true;
            }
        }
    }
    let err = format!("Could not find '{}' in function {}.", assign, fun.name);
    check_fail(prog, &err);
    false
}

pub(crate) fn check_match(prog_str: &str, needle: &str) -> bool {
    if prog_str.contains(needle) {
        return true;
    }
    check_fail_str(prog_str, &format!("expected {}", needle));
    false
}

pub(crate) fn get_summary(
    mut program_info: ProgramInfo,
) -> Result<(Vec<FunctionSummary>, IndexSourceInfo), Error> {
    program_info.program.verify()?;
    let mut facts = IndexFacts::default();
    ssa::transform_program(&mut program_info.program, true);
    let mut source_info = IndexSourceInfo::default();
    codegen_program(
        program_info,
        &mut facts,
        &mut source_info,
        CallResolutionStrategy::Mixed,
    ); //why is that mutable in codegen?
    let result = taint_index(facts);
    Ok((result.summary, source_info))
}

// Isn't it simpler to just assume we will only pass a summary of 1 function?
pub(crate) fn summary_returns_param(
    summary: &[FunctionSummary],
    source_info: &IndexSourceInfo,
    func_name: &str,
    param_num: i16,
) -> bool {
    let id = source_info
        .sites
        .get_function_id(fx::Function(func_name.into()))
        .unwrap();
    summary.iter().any(|r| {
        r.0 == id
            && r.1 == fx::FormalIndex::new(RETURN_INDEX.into())
            && r.3 == fx::FormalIndex::new(param_num.into())
    })
}

pub(crate) fn summary_count(summary: &[FunctionSummary], count: usize) -> bool {
    summary.len() == count
}

pub(crate) fn summary_search(
    summary: &[FunctionSummary],
    from_index: i16,
    from_path: &str,
    to_index: i16,
    to_path: &str,
) -> bool {
    summary.iter().any(|r| {
        r.1 == fx::FormalIndex::new(to_index.into())
            && r.2.to_string() == to_path
            && r.3 == fx::FormalIndex::new(from_index.into())
            && r.4.to_string() == from_path
    })
}
